package nif.niobject.hkx;

import java.io.IOException;
import java.nio.ByteBuffer;

import nif.niobject.hkx.reader.HKXReaderConnector;
import nif.niobject.hkx.reader.InvalidPositionException;

/**

<struct name='hkpConstraintAtom' version='0' signature='0xc132ad1f'>
	<enums>
		<enum name='AtomType' flags='00000000'>
			TYPE_INVALID,   0 
			TYPE_BRIDGE,   1 
			TYPE_SET_LOCAL_TRANSFORMS,   2 
			TYPE_SET_LOCAL_TRANSLATIONS,   3 
			TYPE_SET_LOCAL_ROTATIONS,   4 
			TYPE_BALL_SOCKET,   5 
			TYPE_STIFF_SPRING,   6 
			TYPE_LIN,   7 
			TYPE_LIN_SOFT,   8 
			TYPE_LIN_LIMIT,   9 
			TYPE_LIN_FRICTION,   10 
			TYPE_LIN_MOTOR,   11 
			TYPE_2D_ANG,   12 
			TYPE_ANG,   13 
			TYPE_ANG_LIMIT,   14 
			TYPE_TWIST_LIMIT,   15 
			TYPE_CONE_LIMIT,   16 
			TYPE_ANG_FRICTION,   17 
			TYPE_ANG_MOTOR,   18 
			TYPE_RAGDOLL_MOTOR,   19 
			TYPE_PULLEY,   20 
			TYPE_RACK_AND_PINION,   21 
			TYPE_COG_WHEEL,   22 
			TYPE_SETUP_STABILIZATION,   23 
			TYPE_3D_ANG,   24 
			TYPE_DEFORMABLE_3D_LIN,   25 
			TYPE_DEFORMABLE_3D_ANG,   26 
			TYPE_OVERWRITE_PIVOT,   27 
			TYPE_WHEEL_FRICTION,   28 
			TYPE_CONTACT,   29 
			FIRST_MODIFIER_TYPE,   30 
			TYPE_MODIFIER_SOFT_CONTACT,   30 
			TYPE_MODIFIER_MASS_CHANGER,   31 
			TYPE_MODIFIER_VISCOUS_SURFACE,   32 
			TYPE_MODIFIER_MOVING_SURFACE,   33 
			TYPE_MODIFIER_IGNORE_CONSTRAINT,   34 
			TYPE_MODIFIER_CENTER_OF_MASS_CHANGER,   35 
			LAST_MODIFIER_TYPE,   35 
			TYPE_MAX,   36 
		</enum>
		<enum name='CallbackRequest' flags='00000000'>
			CALLBACK_REQUEST_NONE,   0 
			CALLBACK_REQUEST_NEW_CONTACT_POINT,   1 
			CALLBACK_REQUEST_SETUP_PPU_ONLY,   2 
			CALLBACK_REQUEST_SETUP_CALLBACK,   4 
			CALLBACK_REQUEST_CONTACT_POINT_CALLBACK,   8 
		</enum>
		<enum name='SolvingMethod' flags='00000000'>
			METHOD_STABILIZED,   0 
			METHOD_OLD,   1 
		</enum>
	</enums>
	<members>
		<member name='type' type='enum AtomType' etype='AtomType' offset='0' vtype='TYPE_ENUM' vsubtype='TYPE_UINT16' arrsize='0' flags='FLAGS_NONE 
	</members>
</struct>
*/
public class hkpConstraintAtom {

	enum AtomType {
		TYPE_INVALID, TYPE_BRIDGE, TYPE_SET_LOCAL_TRANSFORMS, TYPE_SET_LOCAL_TRANSLATIONS, //
		TYPE_SET_LOCAL_ROTATIONS, TYPE_BALL_SOCKET, TYPE_STIFF_SPRING, TYPE_LIN, TYPE_LIN_SOFT, //
		TYPE_LIN_LIMIT, TYPE_LIN_FRICTION, TYPE_LIN_MOTOR, TYPE_2D_ANG, TYPE_ANG, TYPE_ANG_LIMIT, //
		TYPE_TWIST_LIMIT, TYPE_CONE_LIMIT, TYPE_ANG_FRICTION, TYPE_ANG_MOTOR, TYPE_RAGDOLL_MOTOR, //
		TYPE_PULLEY, TYPE_RACK_AND_PINION, TYPE_COG_WHEEL, TYPE_SETUP_STABILIZATION, TYPE_3D_ANG, //
		TYPE_DEFORMABLE_3D_LIN, TYPE_DEFORMABLE_3D_ANG, TYPE_OVERWRITE_PIVOT, TYPE_WHEEL_FRICTION, //
		TYPE_CONTACT, FIRST_MODIFIER_TYPE, TYPE_MODIFIER_SOFT_CONTACT, TYPE_MODIFIER_MASS_CHANGER, //
		TYPE_MODIFIER_VISCOUS_SURFACE, TYPE_MODIFIER_MOVING_SURFACE, TYPE_MODIFIER_IGNORE_CONSTRAINT, //
		TYPE_MODIFIER_CENTER_OF_MASS_CHANGER, LAST_MODIFIER_TYPE, TYPE_MAX,
	};

	enum CallbackRequest {
		CALLBACK_REQUEST_NONE, CALLBACK_REQUEST_NEW_CONTACT_POINT, CALLBACK_REQUEST_SETUP_PPU_ONLY, CALLBACK_REQUEST_SETUP_CALLBACK, CALLBACK_REQUEST_CONTACT_POINT_CALLBACK
	};

	enum SolvingMethod {
		METHOD_STABILIZED, METHOD_OLD
	};

	public AtomType type;

	public hkpConstraintAtom(HKXReaderConnector connector, ByteBuffer stream, int classOffset)
			throws IOException, InvalidPositionException {

		int typev = stream.getShort(classOffset + 0);
	}
}